services:
  - type: web
    name: yogin-website
    env: static
    staticPublishPath: dist
    autoDeploy: true

    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    staticHeaders:
      - source: /*
        headers:
          - key: Cache-Control
            value: public, max-age=86400
          - key: Content-Security-Policy
            value: "default-src 'self'; img-src 'self' data: https://*; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';"
          - key: X-Content-Type-Options
            value: "nosniff"
          - key: X-Frame-Options
            value: "DENY"
          - key: X-XSS-Protection
            value: "1; mode=block"
          - key: Referrer-Policy
            value: "strict-origin-when-cross-origin"
          - key: Strict-Transport-Security
            value: "max-age=63072000; includeSubDomains; preload"
          - key: Permissions-Policy
            value: "geolocation=(self), microphone=()"
          - key: Set-Cookie
            value: "SameSite=None; Secure"
