services:
  - type: web
    name: yogin-website
    env: static
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; img-src 'self' data: https://*; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';"
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Strict-Transport-Security
        value: "max-age=63072000; includeSubDomains; preload"
      - path: /*
        name: Permissions-Policy
        value: "geolocation=(self), microphone=()"
      - path: /*
        name: Set-Cookie
        value: "SameSite=None; Secure; HttpOnly"
